
title = "Introduction"

[[section]]
title = "What is Pharos?"
text = `
Pharos is this, and that, and this, but it isn't that.
`


[[section]]
title = "How to get started"
text = `
This is how you get started using Pharos...... blah......
`