title = "Pharos 101 [Dev]"
author = "Brandon Gibson"

theme = "bookly"

[version]
major = 0
minor = 1
patch = 0

[[contents]]
key = "toc"

[[chapter]]
num = 0
file = "intro"

[[chapter]]
num = 1
file = "text"

[[chapter]]
num = 2
file = "code"

[[chapter]]
num = 3
file = "media"



