title = "Pharos 101 [Dev]"
author = "some author"

template = "bookly"

[[contents]]
key = "toc"

[[chapter]]
numeral = 0
source = "intro"

[[chapter]]
numeral = 1
source = "text"

[[chapter]]
numeral = 2
source = "code"

[[chapter]]
numeral = 3
source = "media"



