title = "Pharos 101 [Dev]"
author = "some author"

template = "bookly"

[[chapter]]
title = "Introduction"
key = "intro"

[[chapter]]
chapter = "Chapter 1"
title = "Text"
key = "text"

[[chapter]]
chapter = "Chapter 2"
title = "Code"
key = "code"

[[chapter]]
chapter = "Chapter 3"
title = "Media"
key = "media"


